### ISSUE TITLE
stimulus processing depends on mark htk file

### ISSUE THREAD

**Issue by jihyunbak** [BouchardLab/nsds_lab_to_nwb#14]
This is the error traceback when you run the test `python -u tests/test_build_nwb.py`, with `process_stim=True` switch for the test case 2 (new data):

```python
======================================================================
ERROR: test_build_nwb_case2_new_data_no_stim (__main__.TestCase_Build_NWB)
build NWB but do not write file to disk
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_build_nwb.py", line 65, in test_build_nwb_case2_new_data_no_stim
    nwb_content = nwb_builder.build(process_stim=True)
  File "/home/jhbak/proj/nsds_lab_to_nwb/nsds_lab_to_nwb/nwb_builder.py", line 134, in build
    self.stimulus_originator.make(nwb_content)
  File "/home/jhbak/proj/nsds_lab_to_nwb/nsds_lab_to_nwb/components/stimulus/stimulus_originator.py", line 20, in make
    mark_time_series = self.mark_manager.get_mark_track()
  File "/home/jhbak/proj/nsds_lab_to_nwb/nsds_lab_to_nwb/components/stimulus/mark_manager.py", line 13, in get_mark_track
    mark_track, rate = HtkReader.read_htk(self.mark_path)
  File "/home/jhbak/proj/nsds_lab_to_nwb/nsds_lab_to_nwb/components/htk/htk_reader.py", line 9, in read_htk
    file = HTKFile(path)
  File "/home/jhbak/proj/nsds_lab_to_nwb/nsds_lab_to_nwb/components/htk/readers/htkfile.py", line 190, in __init__
    self.__file = open(self.filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/clusterfs/NSDS_data/hackathon20201201/RatArchive/RVG02/RVG02_B09/mrk11.htk'

———————————————————————————————————
```

Current stimulus processing looks for a `mrk11.htk` file. This is a MARS legacy. Where should we look for the mark files?

**Comment by jihyunbak** [comment]
@VBaratham @jthermiz This probably needs your attention

**Comment by jihyunbak** [comment]
Current version of `MarkManager.get_mark_track()` has

```
def get_mark_track(self, name='recorded_mark'):
    # Read the mark track
    mark_track, rate = HtkReader.read_htk(self.mark_path)
    ...
```

but after the latest update, `self.mark_path` does not exist for TDT data, so this gives an error.

Instead, the last line in the above code snippet should be replaced such that we extract the mark and rate streams from the TDT data itself.

@jthermiz Would this be straightforward for you?

**Comment by JesseLivezey** [comment]
@jihyunbak @jthermiz I have a follow-up PR to #29 that propagates some of the path changes (and I wind up making this change as well). I'm trying to get a TDT block through the whole pipeline and making these fixes as they come up.

**Comment by JesseLivezey** [comment]
see #43
