### ISSUE TITLE
Looks for timit998 -- file does not exisit

### ISSUE THREAD

**Issue by jthermiz** [BouchardLab/nsds_lab_to_nwb#70]
When trying to convert a Timit998 block, the program looks for `timit998.txt` which does not exist. I'm not sure why it looks for that file bc it's not included in `list_of_stimuli.yaml `.

```
Traceback (most recent call last):
  File "/home/jhermiz/software/nsds_lab_to_nwb/scripts/generate_nwb_john.py", line 55, in <module>
    use_htk=use_htk)
  File "/home/jhermiz/software/nsds_lab_to_nwb/nsds_lab_to_nwb/nwb_builder.py", line 98, in __init__
    self.stimulus_originator = StimulusOriginator(self.dataset, self.metadata)
  File "/home/jhermiz/software/nsds_lab_to_nwb/nsds_lab_to_nwb/components/stimulus/stimulus_originator.py", line 16, in __init__
    self.metadata['stimulus'])
  File "/home/jhermiz/software/nsds_lab_to_nwb/nsds_lab_to_nwb/components/stimulus/wav_manager.py", line 16, in __init__
    self.__load_stim_values()
  File "/home/jhermiz/software/nsds_lab_to_nwb/nsds_lab_to_nwb/components/stimulus/wav_manager.py", line 74, in __load_stim_values
    self.stim_configs['stim_values'] = sve.extract()
  File "/home/jhermiz/software/nsds_lab_to_nwb/nsds_lab_to_nwb/components/stimulus/stim_value_extractor.py", line 28, in extract
    os.path.join(self.stim_lib_path, filename)))
  File "<string>", line 1, in <module>
  File "/home/jhermiz/software/nsds_lab_to_nwb/nsds_lab_to_nwb/components/stimulus/stim_value_extractor.py", line 58, in timit_stimulus_values
    with open(csv_file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jhermiz/data/aer/stimulus/TIMIT/timit998.txt'
```

**Comment by JesseLivezey** [comment]
@jthermiz I noticed that the Tone blocks also look for files that are not in `list_of_stimuli.yaml`. I think the stim/mark/wav functionality is the least tested and there is probably some old MARS code that needs to be updated.

**Comment by jihyunbak** [comment]
Did #85 fix this?

**Comment by jihyunbak** [comment]
I'm assuming this is outdated, but anyone please feel free to re-open.
