### ISSUE TITLE
Error related to pandas=1.2.4 (downgrade to 1.2.0 resolved error)

### ISSUE THREAD

**Issue by jthermiz** [BouchardLab/nsds_lab_to_nwb#84]
I received this error when trying to run `generate_nwb.py`. I was able to resolve by downgrading to a lower version 1.2.0. I picked this version arbitrarily and it worked. 

**Error caused by pandas 1.2.4**
```
Traceback (most recent call last):
  File "/home/jhermiz/software/nsds_lab_to_nwb/scripts/generate_nwb_john.py", line 9, in <module>
    from nsds_lab_to_nwb.nwb_builder import NWBBuilder
  File "/home/jhermiz/software/nsds_lab_to_nwb/nsds_lab_to_nwb/nwb_builder.py", line 8, in <module>
    from pynwb import NWBHDF5IO, NWBFile
  File "/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/pynwb/__init__.py", line 9, in <module>
    from hdmf.spec import NamespaceCatalog
  File "/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/hdmf/__init__.py", line 2, in <module>
    from .container import Container, Data, DataRegion
  File "/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/hdmf/container.py", line 10, in <module>
    import pandas as pd
  File "/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/pandas/__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/pandas/core/api.py", line 5, in <module>
    from pandas.core.arrays.integer import (
  File "/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/pandas/core/arrays/__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/pandas/core/arrays/sparse/__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/pandas/core/arrays/sparse/accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/pandas/core/arrays/sparse/array.py", line 20, in <module>
    from pandas.core.dtypes.cast import (
ImportError: cannot import name 'maybe_box_datetimelike' from 'pandas.core.dtypes.cast' (/home/jhermiz/anaconda3/envs/nsds_lab_to_nwb/lib/python3.7/site-packages/pandas/core/dtypes/cast.py)
```

**Comment by jthermiz** [comment]
Can't reproduce anymore.
